name = "Xpress"
uuid = "9e70acf3-d6c9-5be6-b5bd-4e2c73e3e054"
authors = ["Joaquim Dias Garcia <joaquim@psr-inc.con>, Dheepak Krishnamurthy <me@kdheepak.com>, Jose Daniel Lara <jdlara@berkeley.edu>"]
version = "0.9.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
LinQuadOptInterface = "f8899e07-120b-5979-ab1d-7b97bb9e1a48"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"

[compat]
Compat = "2.2.1"
LinQuadOptInterface = "0.6"
MathProgBase = "0.7.7"
julia = "1"
